### ISSUE TITLE
App becomes unresponsive on leaving tab.

### ISSUE THREAD

**Issue by ethanjurman** [bikelomatic-complexity/btc-app#118]
App becomes unresponsive and takes up to as much as 20% of CPU process. This occurs when leaving the tab, and coming back. Only fix is to kill the chrome process.
![image](https://cloud.githubusercontent.com/assets/1131494/13555723/201b2476-e396-11e5-822d-afe00e60fa7d.png)

When I pause the application and `console.error` I appear to be in some anonymous function that is difficult to decipher.
![image](https://cloud.githubusercontent.com/assets/1131494/13555747/8b365ca8-e396-11e5-82ea-f1a01c02a2b4.png)

**Comment by mlw6607** [comment]
Is this issue still occurring?

**Comment by mlw6607** [comment]
This does not occur anymore. I am going to close out this ticket
